// Standard structural placeholders for runtime imports
export const Tutor = {};
export const Booking = {};
export const User = {};

export const CLIENT_SEED_TUTORS = [
  {
    _id: "tutor_01",
    name: "Dr. Sarah Jenkins",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    subject: "Mathematics",
    availableDays: "Mon - Wed",
    availableTime: "4:00 PM - 7:00 PM",
    hourlyFee: 45,
    totalSlots: 5,
    sessionStartDate: "2026-06-01",
    institution: "MIT",
    experience: "8 years",
    location: "Boston",
    teachingMode: "Online",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_02",
    name: "Prof. Michael Chen",
    photoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
    subject: "Physics",
    availableDays: "Tue - Thu",
    availableTime: "5:00 PM - 8:00 PM",
    hourlyFee: 50,
    totalSlots: 4,
    sessionStartDate: "2026-06-05",
    institution: "Stanford University",
    experience: "12 years",
    location: "San Francisco",
    teachingMode: "Both",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_03",
    name: "Emily Rodriguez",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
    subject: "Chemistry",
    availableDays: "Sun - Tue",
    availableTime: "3:00 PM - 6:00 PM",
    hourlyFee: 40,
    totalSlots: 3,
    sessionStartDate: "2026-05-25",
    institution: "UC Berkeley",
    experience: "5 years",
    location: "Berkeley",
    teachingMode: "Online",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_04",
    name: "Dr. David Kim",
    photoUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400",
    subject: "Biology",
    availableDays: "Wed - Fri",
    availableTime: "5:00 PM - 8:00 PM",
    hourlyFee: 45,
    totalSlots: 0,
    sessionStartDate: "2026-06-10",
    institution: "Harvard University",
    experience: "10 years",
    location: "Cambridge",
    teachingMode: "Offline",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_05",
    name: "James Wilson",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
    subject: "Computer Science",
    availableDays: "Mon - Thu",
    availableTime: "6:00 PM - 9:00 PM",
    hourlyFee: 55,
    totalSlots: 8,
    sessionStartDate: "2026-05-20",
    institution: "Georgia Tech",
    experience: "6 years",
    location: "Atlanta",
    teachingMode: "Both",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_06",
    name: "Sophia Martinez",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
    subject: "English",
    availableDays: "Sat - Sun",
    availableTime: "10:00 AM - 1:00 PM",
    hourlyFee: 35,
    totalSlots: 6,
    sessionStartDate: "2026-06-12",
    institution: "Columbia University",
    experience: "4 years",
    location: "New York",
    teachingMode: "Online",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_07",
    name: "Alexander Wright",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400",
    subject: "Other",
    availableDays: "Mon - Wed",
    availableTime: "5:00 PM - 8:00 PM",
    hourlyFee: 48,
    totalSlots: 2,
    sessionStartDate: "2026-06-03",
    institution: "Oxford University",
    experience: "7 years",
    location: "London",
    teachingMode: "Both",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_08",
    name: "Prof. Jessica Vance",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
    subject: "Biology",
    availableDays: "Tue - Thu",
    availableTime: "2:00 PM - 5:00 PM",
    hourlyFee: 52,
    totalSlots: 6,
    sessionStartDate: "2026-06-08",
    institution: "Yale University",
    experience: "11 years",
    location: "New Haven",
    teachingMode: "Online",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_09",
    name: "Daniel Thorne",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    subject: "Physics",
    availableDays: "Fri - Sat",
    availableTime: "3:00 PM - 6:00 PM",
    hourlyFee: 47,
    totalSlots: 5,
    sessionStartDate: "2026-06-11",
    institution: "Princeton University",
    experience: "6 years",
    location: "Princeton",
    teachingMode: "Both",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_10",
    name: "Dr. Maria Santos",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
    subject: "Chemistry",
    availableDays: "Mon - Wed",
    availableTime: "1:00 PM - 4:00 PM",
    hourlyFee: 46,
    totalSlots: 4,
    sessionStartDate: "2026-06-02",
    institution: "Caltech",
    experience: "9 years",
    location: "Pasadena",
    teachingMode: "Offline",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_11",
    name: "Liam O'Connor",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
    subject: "Computer Science",
    availableDays: "Sat - Sun",
    availableTime: "4:00 PM - 7:00 PM",
    hourlyFee: 58,
    totalSlots: 7,
    sessionStartDate: "2026-05-30",
    institution: "University of Cambridge",
    experience: "5 years",
    location: "Cambridge",
    teachingMode: "Online",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  },
  {
    _id: "tutor_12",
    name: "Dr. Chloe Dupont",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    subject: "Other",
    availableDays: "Mon - Thu",
    availableTime: "9:00 AM - 12:00 PM",
    hourlyFee: 42,
    totalSlots: 3,
    sessionStartDate: "2026-06-15",
    institution: "Sorbonne University",
    experience: "10 years",
    location: "Paris",
    teachingMode: "Both",
    createdByUserEmail: "admin@mediqueue.org",
    createdByUserName: "Admin Director"
  }
];
